"""Branch, commit, push, and open a PR for agent-generated changes.

Called after a team run that passes verification. Deterministic subprocess
calls — no agent in the loop. Designed so individual steps can fail
without raising: the returned dict reports what was accomplished so the
CLI can surface a clear summary.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field


@dataclass
class PRResult:
    branch: str = ""
    committed: bool = False
    pushed: bool = False
    pr_url: str = ""
    skipped: str = ""
    errors: list[str] = field(default_factory=list)

    def summary(self) -> str:
        if self.skipped:
            return f"[pr] Skipped: {self.skipped}"
        lines = [f"[pr] Branch: {self.branch or '(unknown)'}"]
        lines.append(f"[pr] Commit: {'yes' if self.committed else 'no'}")
        lines.append(f"[pr] Push:   {'yes' if self.pushed else 'no'}")
        if self.pr_url:
            lines.append(f"[pr] PR:     {self.pr_url}")
        for err in self.errors:
            lines.append(f"[pr] Error: {err}")
        return "\n".join(lines)


def _run(cmd: list[str], cwd: str) -> tuple[int, str, str]:
    p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return p.returncode, p.stdout, p.stderr


def _slugify(text: str, max_len: int = 50) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    return (s[:max_len].rstrip("-")) or "agent-task"


def _has_changes(cwd: str) -> bool:
    rc, out, _ = _run(["git", "status", "--porcelain"], cwd)
    return rc == 0 and bool(out.strip())


def _current_branch(cwd: str) -> str:
    rc, out, _ = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd)
    return out.strip() if rc == 0 else ""


def _is_git_repo(cwd: str) -> bool:
    rc, _, _ = _run(["git", "rev-parse", "--is-inside-work-tree"], cwd)
    return rc == 0


def _split_commit_message(message: str) -> tuple[str, str]:
    """Split a commit message into (subject, body). Subject is the first line."""
    lines = message.strip().splitlines()
    if not lines:
        return "", ""
    subject = lines[0].strip()[:72]
    body_lines = lines[1:]
    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)
    return subject, "\n".join(body_lines).strip()


def create_pr(
    task: str,
    prd: str,
    project_dir: str,
    branch_prefix: str = "agent/",
    commit_message: str | None = None,
) -> PRResult:
    """Branch, commit, push, and open a PR for changes in `project_dir`.

    - If there are no uncommitted changes, returns a skipped result.
    - If currently on main/master, creates a new branch; otherwise reuses
      the current branch.
    - `git add -A` respects .gitignore, so venvs/__pycache__ are safe.
    - If `commit_message` is supplied (e.g., authored by the exec/fix
      agent), it is used verbatim for the commit. Otherwise the title
      falls back to the task string.
    - PR title is the commit subject. PR body is the commit body plus the
      PRD for reviewer context.
    - Uses `gh pr create` for the final step. Falls back to commit+push
      if `gh` is missing.
    """
    result = PRResult()

    if not _is_git_repo(project_dir):
        result.skipped = f"{project_dir} is not a git repo"
        return result

    if not _has_changes(project_dir):
        result.skipped = "no changes to commit"
        return result

    current = _current_branch(project_dir)
    if current in ("main", "master", ""):
        branch = f"{branch_prefix}{_slugify(task)}"
        rc, _, err = _run(["git", "checkout", "-b", branch], project_dir)
        if rc != 0:
            result.errors.append(f"checkout -b {branch}: {err.strip()}")
            return result
    else:
        branch = current
    result.branch = branch

    _run(["git", "add", "-A"], project_dir)

    if commit_message:
        subject, commit_body = _split_commit_message(commit_message)
    else:
        subject, commit_body = "", ""
    if not subject:
        subject = (task.splitlines()[0].strip() if task else "Agent-generated changes")[:72]
        subject = subject or "Agent-generated changes"

    pr_body_parts = []
    if commit_body:
        pr_body_parts.append(commit_body)
    if prd:
        pr_body_parts.append(f"---\n\n## Original PRD\n\n{prd}")
    pr_body = "\n\n".join(pr_body_parts) or "Generated by multi-agent orchestration."

    commit_full = subject if not commit_body else f"{subject}\n\n{commit_body}"
    rc, _, err = _run(
        ["git", "commit", "-m", commit_full], project_dir
    )
    if rc != 0:
        result.errors.append(f"commit: {err.strip()}")
        return result
    result.committed = True

    rc, _, err = _run(
        ["git", "push", "-u", "origin", branch], project_dir
    )
    if rc != 0:
        result.errors.append(f"push: {err.strip()}")
        return result
    result.pushed = True

    if shutil.which("gh") is None:
        result.skipped = "gh not installed — commit pushed, open PR manually"
        return result

    rc, out, err = _run(
        ["gh", "pr", "create", "--title", subject, "--body", pr_body],
        project_dir,
    )
    if rc != 0:
        result.errors.append(f"gh pr create: {err.strip()}")
        return result
    result.pr_url = out.strip().splitlines()[-1] if out.strip() else ""
    return result
